# -*- coding: utf-8 -*-
"""DVSKILL-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-5QmqE9lx8qecCHAXiJiefYCMjZx_wC
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/samplesuperstore.csv")
df.head()

print(df.shape)
df.info()

df.describe()

df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

for col in ['Category', 'Sub-Category', 'Segment']:
    df[col] = df[col].str.strip().str.title()

df[['Category', 'Sub-Category', 'Segment']].head()

df.isnull().sum()

df = df.drop_duplicates()
print("Shape:", df.shape)

df = df.drop_duplicates()
print("Shape:", df.shape)

df['Shipping Days'] = (df['Ship Date'] - df['Order Date']).dt.days
df[['Order Date', 'Ship Date', 'Shipping Days']].head()

df[['Sales', 'Quantity', 'Discount', 'Profit', 'Shipping Days']].describe()

df.groupby('Category')['Sales'].sum().plot(kind='bar')
plt.title('Sales by Category')
plt.ylabel('Sales')
plt.show()

df.groupby('Category')['Profit'].sum().plot(kind='bar')
plt.title('Profit by Category')
plt.ylabel('Profit')
plt.show()

df.groupby('Region')['Sales'].sum().plot(kind='bar')
plt.title('Sales by Region')
plt.ylabel('Sales')
plt.show()

df.groupby(df['Order Date'].dt.year)['Sales'].sum().plot(kind='line', marker='o')
plt.title('Yearly Sales Trend')
plt.ylabel('Sales')
plt.show()

sns.heatmap(
    df[['Sales', 'Quantity', 'Discount', 'Profit']].corr(),
    annot=True
)
plt.title('Correlation Heatmap')
plt.show()

df.head()

df.to_csv('cleaned_superstore.csv', index=False)
print("Cleaned dataset saved!")